export const Types = {
  // global
  FETCH_ALL_STOPS_SUCCESS: "FETCH_ALL_STOPS_SUCCESS",
  FETCH_ALL_STOPS_ERROR: "FETCH_ALL_STOPS_ERROR",

  // searchForm
  INPUT_VALUE_FROM: "INPUT_VALUE_FROM",
  INPUT_VALUE_TO: "INPUT_VALUE_TO",
  INPUT_DATE: "INPUT_DATE",
  DECREMENT_AMOUNT_PASSANGER: "DECREMENT_AMOUNT_PASSANGER",
  INCREMENT_AMOUNT_PASSANGER: "INCREMENT_AMOUNT_PASSANGER",

  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  FETCH_TRIPS_START: "FETCH_TRIPS_START",
  FETCH_TRIPS_SUCCESS: "FETCH_TRIPS_SUCCESS",
  FETCH_TRIPS_ERROR: "FETCH_TRIPS_ERROR",
  // CHANGE_IS_VISIBLE_TRIPS: "CHANGE_IS_VISIBLE_TRIPS",

  GET_TRIPS_INFO: "GET_TRIPS_INFO",

  CHANGE_IS_VISIBLE_ORDER: "CHANGE_IS_VISIBLE_ORDER",
  FETCH_ORDER_INFO: "FETCH_ORDER_INFO",
  AMOUNT_PASSANGER: "AMOUNT_PASSANGER",
  SEND_INFO_PASSANGER: "SEND_INFO_PASSANGER",
};
