export const Types = {
  // global
  START_LOADER: "START_LOADER",
  GET_ERROR: "GET_ERROR",
  FINISH_LOADER: "FINISH_LOADER",

  // searchForm
  INPUT_VALUE_FROM: "INPUT_VALUE_FROM",
  INPUT_VALUE_TO: "INPUT_VALUE_TO",
  INPUT_DATE: "INPUT_DATE",
  DECREMENT_AMOUNT_PASSANGER: "DECREMENT_AMOUNT_PASSANGER",
  INCREMENT_AMOUNT_PASSANGER: "INCREMENT_AMOUNT_PASSANGER",
  TIME: "TIME",
  IS_OPEN_FROM: "IS_OPEN_FROM",
  IS_OPEN_TO: "IS_OPEN_TO",
  IS_OPEN_DATE: "IS_OPEN_DATE",

  //  language
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //  trips
  FETCH_TRIPS_SUCCESS: "FETCH_TRIPS_SUCCESS",
  GET_TRIPS_INFO: "GET_TRIPS_INFO",
  FETCH_TICKET: "FETCH_TICKET",
  GET_SORT_TYPE: "GET_SORT_TYPE",
  GET_SHOW_SORT_BOX: "GET_SHOW_SORT_BOX",
  GET_SHOW_SORT_BOX_DOUBLE: "GET_SHOW_SORT_BOX_DOUBLE",
  GET_SORT_TYPE_SINGLE: "GET_SORT_TYPE_SINGLE",
  GET_SORT_TYPE_DOUBLE: "GET_SORT_TYPE_DOUBLE",

  // order
  FETCH_TRIP_KEYS: "FETCH_TRIP_KEYS",
  AMOUNT_PASSANGER: "AMOUNT_PASSANGER",
  ADDITIONAL_SERVICES: "ADDITIONAL_SERVICES",
};
