export const Types = {
  FETCH_ALL_STOPS_SUCCESS: 'FETCH_ALL_STOPS_SUCCESS',
  GET_FILTERED_STOPS: 'GET_FILTERED_STOPS',
  INPUT_VALUE_FROM: 'INPUT_VALUE_FROM',
  INPUT_VALUE_TO: 'INPUT_VALUE_TO',

  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
};
