export const Types = {
  FETCH_ALL_STOPS_SUCCESS: 'FETCH_ALL_STOPS_SUCCESS',
  FETCH_ALL_STOPS_ERROR: 'FETCH_ALL_STOPS_ERROR',

  GET_FILTERED_STOPS: 'GET_FILTERED_STOPS',
  INPUT_VALUE_FROM: 'INPUT_VALUE_FROM',
  INPUT_VALUE_TO: 'INPUT_VALUE_TO',
  GET_CLASS_NAME:'GET_CLASS_NAME',
  IS_VISIBLE:'IS_VISIBLE',

  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
};
