export const messages = {
  UK: {
    login: "Логін",
    password: "Пароль",
    signIn: "Увійти",
    authorization: "Авторизація",
    required: "Це поле необхідно заповнити",
    errorAuth: "Не вірний логін або пароль",
    searchByNumber: "Знайти замовлення по номеру",
    searchActiv: "Всі активні замовлення",
    searchByPeriod: "Замовлення за період",
    from: "з",
    to: "по",
    search: "Пошук",
    welcome: "Вітаємо!",
    start: "Для початку роботи введіть свій номер телефону",
    send: "Відправити",
    confirm: "Підтвердіть номер",
    sms: "СМС з кодом підтвердження відправлено на номер ",
    myTickets: "Мої квитки"
  },
  RU: {
    login: "Логин",
    password: "Пароль",
    signIn: "Войти",
    authorization: "Авторизация",
    exit: "Sign out",
    required: "Это поле необходимо заполнить",
    errorAuth: "Не верный логин или пароль",
    searchByNumber: "Найти заказ по номеру",
    searchActiv: "Все активные заказы",
    searchByPeriod: "Найти заказы за период",
    from: "с",
    to: "по",
    search: "Поиск",
    wellcome: "Добро пожаловать!",
    start: "Для начала работы введите свой номер телефона",
    send: "Отправить",
    confirm: "Подтвердите номер",
    sms: "СМС с кодом подтверждения отправлено на номер",
    myTickets: "Мои билеты"
  },

  EN: {
    login: "Login",
    password: "Password",
    signIn: "Sign in",
    authorization: "Authorization",
    exit: "Sign out",
    required: "This field is required",
    errorAuth: "Wrong login or password",
    searchByNumber: "Find an order by number",
    searchActiv: "All active orders",
    searchByPeriod: "Find orders for a period",
    from: "from",
    to: "to",
    search: "Search",
    wellcome: "Welcome!",
    start: "Enter your phone number to get started",
    send: "Send",
    confirm: "Confirm number",
    sms: "SMS with confirmation code sent to number",
    myTickets: "My tickets"
  },
  PL: {
    login: "Login",
    password: "Password",
    signIn: "Sign in",
    authorization: "Authorization",
    exit: "Sign out",
    required: "This field is required",
    errorAuth: "Wrong login or password",
    searchByNumber: "Find an order by number",
    searchActiv: "All active orders",
    searchByPeriod: "Find orders for a period",
    from: "from",
    to: "to",
    search: "Search",
    wellcome: "Witamy!",
    start: "Wprowadź swój numer telefonu, aby rozpocząć",
    send: "Wysłać",
    confirm: "Potwierdź numer",
    sms: "SMS z kodem potwierdzającym wysłany na numer",
    myTickets: "Moje bilety"
  },
};
