export const messages = {
  UK: {
    login: "Логін",
    password: "Пароль",
    signIn: "Увійти",
    authorization: "Авторизація",
    required: "Це поле необхідно заповнити",
    errorAuth:"Не вірний логін або пароль",
    searchByNumber: "Знайти замовлення по номеру",
    searchActiv:"Всі активні замовлення",
    searchByPeriod: "Замовлення за період",
    from: "з",
    to:"по",
    search: "Пошук",

  },
  RU: {
    login: "Логин",
    password: "Пароль",
    signIn: "Войти",
    authorization: "Авторизация",
    exit: "Sign out",
    required: "Это поле необходимо заполнить",
    errorAuth:"Не верный логин или пароль",
    searchByNumber: "Найти заказ по номеру",
    searchActiv:"Все активные заказы",
    searchByPeriod: "Найти заказы за период",
    from: "с",
    to:"по",
    search: "Поиск",

  },
  EN:{
    login: "Login",
    password: "Password",
    signIn: "Sign in",
    authorization: "Authorization",
    exit: "Sign out",
    required: "This field is required",
    errorAuth:"Wrong login or password",
    searchByNumber: "Find an order by number",
    searchActiv:"All active orders",
    searchByPeriod: "Find orders for a period",
    from: "from",
    to:"to",
    search: "Search",

  },
  PL: {
    login: "Login",
    password: "Password",
    signIn: "Sign in",
    authorization: "Authorization",
    exit: "Sign out",
    required: "This field is required",
    errorAuth:"Wrong login or password",
    searchByNumber: "Find an order by number",
    searchActiv:"All active orders",
    searchByPeriod: "Find orders for a period",
    from: "from",
    to:"to",
    search: "Search",

  },
};

