export const messages = {
  UK: {
    title: "Квитки на автобус",
    subtitle: "по Україні, Польщі, Європі",
    iconItem1: "Гарантія низької вартості",
    iconItem2: "Безпечна оплата картою",
    iconItem3: "Цілодобова служба підтримки",
    iconItem4: "Система знижок і бонусів",
    iconItem5: "смс інформування",
    searchBtn: "Пошук квитків",
    inputAmount: "Пасажири",
    from: "Звідки",
    to: "Куди",
  },
  RU: {
    title: "Билеты на автобус",
    subtitle: "по Украине, Польше, Европе",
    iconItem1: "Гарантия низкой цены",
    iconItem2: "Безопасная оплата картой",
    iconItem3: "Круглосуточная служба поддержки",
    iconItem4: "Система скидок и бонусов",
    iconItem5: "Смс информирование",
    searchBtn: "Поиск билетов",
    inputAmount: "Пассажиры",
    from: "Откуда",
    to: "Куда",
  },
  EN: {
    title: "Bus ticket",
    subtitle: "in Ukraine, Poland, Europe",
    iconItem1: "Low price guarantee",
    iconItem2: "Safe card payment",
    iconItem3: "24/7 customer support",
    iconItem4: "Вiscounts and bonuses",
    iconItem5: "SMS informing",
    searchBtn: "Search",
    inputAmount: "Passengers",
    from: "from",
    to: "to",
  },
  PL: {
    title: "Bilety autobusowe",
    subtitle: "na Ukrainie, w Polsce, Europie",
    iconItem1: "Gwarancja niskiej ceny",
    iconItem2: "Bezpieczna płatność kartą",
    iconItem3: "Obsługa klienta 24/7",
    iconItem4: "System rabatów i bonusów",
    iconItem5: "Informowanie SMS",
    searchBtn: "Szukaj",
    inputAmount: "Pasażerowie",
    from: "Skąd",
    to: "Dokąd",
  },
};
