export const messanges = {
  UK: {
    main: "Головна",
    routs: "Маршрути",
    info: "Інформація",
    contacts: "Контакти",
    mobile: "Мобільні додатки",
    login: "Логін: ",
    password: "Пароль",
    errorText: "Не вірний логін або пароль",
    signIn: "Увійти",
    authorization: "Авторизація",
    exit: "Вихід",
    required: "Це поле необхідно заповнити",
    cabinet: "Особистий кабінет"
  },
  RU: {
    main: "Главная",
    routs: "Маршруты",
    info: "Информация",
    contacts: "Контакты",
    mobile: "Мобильные приложения",
    login: "Логин: ",
    password: "Пароль",
    errorText: "Не верный логин или пароль",
    signIn: "Войти",
    authorization: "Aвторизация",
    exit: "Выход",
    required: "Это поле необходимо заполнить",
    cabinet: "Личный кабинет"
  },
  EN: {
    main: "Home",
    routs: "Route map",
    info: "Information",
    contacts: "Contacts",
    mobile: "Mobile applications",
    login: "Login: ",
    password: "Password",
    errorText: "Incorrect login or password",
    signIn: " Sign in",
    authorization: "Authorization",
    exit: "Sign out",
    required: "This field is required",
    cabinet: "Personal area"
  },
  PL: {
    main: "Główna",
    routs: "Mapa",
    info: "Informacja",
    contacts: "Łączność",
    mobile: "Aplikacje mobilne",
    login: "Login: ",
    password: "Hasło",
    errorText: "Nieprawidłowy login lub hasło",
    signIn: "Zaloguj się",
    authorization: "Upoważnienie",
    exit: "Exit",
    required: "to pole jest wymagane",
    cabinet: "Obszar osobisty"
  },
};
