export const messages = {
  EN: {
    title: "Passenger data",
    departure: "Departure",
    arrival: "Arrival",
    buttonAdd: "Add passenger",
    customer: "Customer details*:",
    offer: "I accept the terms ",
    offerSpan: "of the public offer ",
    buy: "To the payment",
    myData: "and I consent to the processing ",
    myDataSpan: "personal data",
    requared: "*All fields are required",
    numTel: "** Indicate the current phone number for communication in case of flight changes",
    details: "Order details",
    pay: "Payable: ",
  },
  RU: {
    title: "Данные о пассажирах",
    departure: "Отправление",
    arrival: "Прибытие",
    buttonAdd: "Добавить пассажира",
    customer: "Данные о покупателе*:",
    offer: "Я принимаю условия ",
    offerSpan: "публичной оферты ",
    buy: "Перейти к оплате",
    myData: "и даю согласие на обработку ",
    myDataSpan: "персональных данных",
    requared: "*Все поля обязательны к заполнению",
    numTel: "**Укажите актуальный номер телефона для связи в случае изменений рейса",
    details: "Детали заказа",
    pay: "К оплате: ",
  },
  UK: {
    title: "Відомості про пасажирів",
    departure: "Відправлення",
    arrival: "Прибуття",
    buttonAdd: "Додати пасажира",
    customer: "Відомості про покупця *:",
    offer: "Я приймаю умови ",
    offerSpan: "публічної оферти ",
    buy: "Перейти до оплати",
    myData: "і даю згоду на обробку ",
    myDataSpan: "персональних даних",
    requared: "*Всі поля обов'язкові до заповнення",
    numTel: "**Вкажіть актуальний номер телефону для зв'язку в разі змін рейсу",
    details: "Деталі замовлення",
    pay: "До сплати: ",
  },
  PL: {
    title: "Dane pasażera",
    departure: "Wyjazd",
    arrival: "Przyjazd",
    buttonAdd: "Dodaj pasażera",
    customer: "Dane kupującego *:",
    offer: "Akceptuję warunki ",
    offerSpan: "oferty publicznej ",
    buy: "Przejdź do płatności",
    myData: "i wyrażam zgodę na przetwarzanie ",
    myDataSpan: "danych osobowych",
    requared: "*Wszystkie pola są wymagane",
    numTel: "**Podaj aktualny numer telefonu do komunikacji w przypadku zmiany lotu",
    details: "Szczegóły zamówienia",
    pay: "Do zapłaty: ",
  },
};
