export const messages = {
  UK: {
    title: "Відомості про пасажирів",
    departure: "Відправлення",
    arrival: "Прибуття",
    buttonAdd: "Додати пасажира",
    customer: "Відомості про покупця *:",
    offer: "Я приймаю умови ",
    offerSpan: "публічної оферти ",
    buy: "Перейти до оплати",
    myData: "і даю згоду на обробку ",
    myDataSpan: "персональних даних",
    requared: "*Всі поля обов'язкові до заповнення",
    numTel: "**Вкажіть актуальний номер телефону для зв'язку в разі змін рейсу",
    details: "Деталі замовлення",
    pay: "До сплати: ",
    name: "Ім'я",
    phone: "Телефон",
    surname: "Прізвище",
    patronymic: "По батькові",
    document: "Документ",
    citizenship: "Громадянство",
    number: "Номер",
    series: "Серія",
    birthday: "Дата народження",
    sex: "Стать:",
    man: "чоловіча",
    feman: "жіноча",
    latin: " (лише латинськими літерами)",
    ticket: "Квиток:",
    total: "Всього:",
    additionalService: "Додаткові послуги:",
    order: "Ваше замовлення:",
    uah: " грн",
    requare: "це поле необхідно заповнити",
    dontcorectlyEmail: "не коректний email",
    dontcorectlyPhone:"не коректний номер телефону",
    min2: "мінімум два символи",
    dontinclud: "поле не може містити #! '№%:? * / {|} <>",
  },
  RU: {
    title: "Данные о пассажирах",
    departure: "Отправление",
    arrival: "Прибытие",
    buttonAdd: "Добавить пассажира",
    customer: "Данные о покупателе*:",
    offer: "Я принимаю условия ",
    offerSpan: "публичной оферты ",
    buy: "Перейти к оплате",
    myData: "и даю согласие на обработку ",
    myDataSpan: "персональных данных",
    requared: "*Все поля обязательны к заполнению",
    numTel: "**Укажите актуальный номер телефона для связи в случае изменения рейса.",
    details: "Детали заказа",
    pay: "Перейти к оплате",
    name: "Имя",
    phone: "Телефон",
    surname: "Фамилия",
    patronymic: "Отчество",
    document: "Документ",
    citizenship: "Гражданство",
    number: "Номер",
    series: "Серия",
    birthday: "Дата рождения",
    sex: "Пол:",
    man: "Мужской",
    feman: "Женский",
    latin: " (латинскими буквами)",
    ticket: "Билет:",
    total: "Всего:",
    additionalService: "Дополнительные услуги:",
    order: "Ваш заказ:",
    uah: " грн",
    requare: "Это поле необходимо заполнить",
    dontcorectlyEmail: "Некорректный email",
    dontcorectlyPhone: "Некорректный номер телефона",
    min2: "Не менее двух символов",
    dontinclud: "Поле не может содержать #! '№%:? * / {|} <>",
  },

  EN: {
    title: "Passenger data",
    departure: "Departure",
    arrival: "Arrival",
    buttonAdd: "Add passenger",
    customer: "Customer details*:",
    offer: "I accept the terms ",
    offerSpan: "of the public offer ",
    buy: "Proceed to payment",
    myData: "and I consent to the processing ",
    myDataSpan: "personal data",
    requared: "*All fields are required",
    numTel:
      "**Please specify the current telephone number for communication in a case of the voyage change.",
    details: "Order details",
    pay: "Payable: ",
    name: "Name",
    surname: "Surname",
    phone: "Telephone number",
    patronymic: "Patronymic",
    document: "Document",
    citizenship: "Citizenship",
    number: "Number",
    series: "Series",
    birthday: "",
    sex: "Sex:",
    man: "Male",
    feman: "Female",
    latin: "Only in Latin letters",
    ticket: "Ticket: ",
    total: "Total:",
    additionalService: "Additional services:",
    order: "Your order:",
    uah: " uah",
    requare: "This field is required",
    dontcorectlyEmail: "Invalid email",
    dontcorectlyPhone:"Invalid phone number",
    min2: "At least two characters",
    dontinclud: "The field cannot contain #! '№% :? * / {|} <>",
  },
  PL: {
    title: "Dane pasażera",
    departure: "Wyjazd",
    arrival: "Przyjazd",
    buttonAdd: "Dodaj pasażera",
    customer: "Dane kupującego *:",
    offer: "Akceptuję warunki ",
    offerSpan: "oferty publicznej ",
    buy: "Przejdź do płatności",
    myData: "i wyrażam zgodę na przetwarzanie ",
    myDataSpan: "danych osobowych",
    requared: "*Wszystkie pola musza byc  wypełnione",
    numTel:
      "**Podaj aktualny numer telefonu, z którym należy się skontaktować w przypadku zmiany lotu.",
    details: "Szczegóły zamówienia",
    pay: "Przejdź do kasy: ",
    name: "Name",
    phone: "Telefon",
    surname: "Nazwisko",
    patronymic: "Patronimiczny",
    document: "Akta",
    citizenship: "Obywatelstwo",
    number: "Numer",
    series: "Seria",
    birthday: "Data urodzenia",
    sex: "Płec:",
    man: "Мęski",
    feman: "Żeńska",
    latin: " (tylko literami łacińskimi)",
    ticket: "Bilet",
    total: "Сałkowity",
    additionalService: "Dodatkowe usługi:",
    order: "Twoje zamówienie",
    uah: " uah",
    requare: "to pole jest wymagane",
    dontcorectlyEmail: "nieprawidłowy email",
    dontcorectlyPhone: "nieprawidłowy numer telefonu",
    min2: "co najmniej dwie postacie",
    dontinclud: "pole nie może zawierać #! '№% :? * / {|} <>",
  },
};
 








