export const messages = {
  UK: {
    trip: "Маршрут:",
    passangersData: "Відомості про пасажирів",
    cost: "Вартість: ",
    passenger: "Пасажир №:",
    name: "Ім'я",
    surname: "Прізвище",
    phone: "Телефон",
    endTime: "Для оформлення замовлення оплатіть його до: ",
    securityStandart:
      "Ваші платіжні та особисті дані надійно захищені відповідно до міжнародних стандартів безпеки",
    addservices: "Додаткові послуги",
    summ: "Сума до сплати: ",
    pay: "сплатити за допомогою:",
    return: "Умови повернення",
    booking: "Час актуального бронювання закінчився",
    goHome: "Повернутися на головну сторінку",
    uah: "грн",
    success: "Оплата пройшла успішно!!!",
    fail: "При оформленні квитка виникла помилка",
    number: "Номер Вашого замовлення ",
    call: "Звяжіться з службою підтримки за телефоном: ",
    download: "завантажити квиток",
    addBtn: "Додати до замовлення",
    status: "Статус",
    order: "Номер замовлення: ",
  },
  RU: {
    trip: "Маршрут:",
    passangersData: "Данные о пассажирах:",
    cost: "Стоимость: ",
    passenger: "Пассажир №:",
    name: "Имя",
    surname: "Фамилия",
    phone: "Телефон",
    endTime: "Для оформления заказа оплатите его до: ",
    securityStandart:
      "Ваши платежные и личные данные надежно защищены в соответствии с международными стандартами безопасности.",
    addservices: "Дополнительные услуги",
    summ: "Сумма к оплате: ",
    pay: "Оплатить с помощью",
    return: "Условия возврата",
    booking: "Время актуального бронирования истекло",
    goHome: "Вернуться на главную страницу ",
    uah: "грн",
    success: "Оплата прошла успешно !!!",
    fail: "При оформлении билета возникла ошибка",
    number: "Номер вашего заказа",
    call: "Свяжитесь со службой поддержки по телефону: ",
    download: "скачать билет",
    addBtn: "Добавить к заказу",
    status: "Статус",
    order: "Номер заказа: ",
  },
  
  EN: {
    trip: "Route:",
    passangersData: "Passenger data:",
    cost: " Cost:",
    passenger: "Passenger №:",
    name: "Name",
    surname: "Surname",
    phone: "Phone",
    endTime: "To place an order, pay for it before: ",
    securityStandart:
      "Your payment and personal data are reliably protected in accordance with international security standards.",
    addservices: "Additional services",
    summ: "Amount to pay",
    pay: "Pay with help",
    return: "Return conditions",
    booking: "Current booking time has expired",
    goHome: "Return to the homepage",
    uah: "uah",
    success: "The payment was successful !!!",
    fail: "An error occurred while issuing a ticket",
    number: "Your order number",
    call: "Contact support by phone: ",
    download: "download your ticket",
    addBtn: "Add to order",
    status: "Status",
    order: "Order number: ",
  },
  
  PL: {
    trip: "Trasa:",
    passangersData: "Dane pasażera:",
    cost: "Koszt: ",
    passenger: "Pasażera №:",
    name: "Nazwa",
    surname: "Nazwisko",
    phone: "Telefon",
    endTime: "Aby złożyć zamówienie, opłać je wcześniej: ",
    securityStandart:
      "Twoje płatności i dane osobowe są bezpiecznie chronione zgodnie z międzynarodowymi standardami bezpieczeństwa.",
    addservices: "Dodatkowe usługi",
    summ: "Kwota do zapłaty",
    pay: "Płacić z pomocą",
    return: "Warunki zwrotu",
    booking: "Aktualny czas rezerwacji upłynął",
    goHome: "Wróć do strony głównej",
    uah: "uah",
    success: "Płatność się powiodła !!!",
    fail: "Wystąpił błąd podczas wystawiania biletu",
    number: "Numer Twojego zamówienia",
    call: "Skontaktuj się z obsługą klienta telefonicznie:",
    download: "pobierz bilet",
    addBtn: "Dodać do zamówienia",
    status: "Status",
    order: "Order number: ",
  },
};







 