export const messages = {
  UK: {
    trip: "Маршрут:",
    passangersData: "Відомості про пасажирів",
    cost: "Вартість: ",
    passenger: "Пасажир №:",
    name: "Ім'я",
    surname: "Прізвище",
    phone: "Телефон",
    endTime: "Для оформлення замовлення оплатіть його до: ",
    securityStandart:
      "Ваші платіжні та особисті дані надійно захищені відповідно до міжнародних стандартів безпеки",
    addservices: "Додаткові послуги",
    summ: "Сума до сплати: ",
    pay: "сплатити за допомогою:",
    return: "Умови повернення",
    booking: "Час актуального бронювання закінчився",
    goHome: "Повернутися на головну сторінку",
    uah: "грн",
    success: "Оплата пройшла успішно!!!",
    fail: "При оформленні квитка виникла помилка",
    number: "Номер Вашого замовлення ",
    call: "Звяжіться з службою підтримки за телефоном: ",
    download: " тут*",
    addBtn: "Додати до замовлення",
    status: "Статус",
    order: "Номер замовлення: ",
    forDownload: "Для отримання квитка та додаткового супроводу встановіть додаток ",
    or: " або завантажити квиток",
    dontPrint: "*Для посадки роздруковувати квиток не обов'язково",
    errorPayed: "При оплаті виникла помилка",
    errorOrder: "Не вдається знайти замовлення",
    errorTransaction: "Не вдається знайти платіжну операцію",
    errorError: "Упс..! Щось пішло не так",
    use: "використати ",
    bonuses: " бонусів",
    payBonuses: "Cплатити бонусами",
    googleError: "Сталась помилка при оплаті"
  },
  RU: {
    trip: "Маршрут:",
    passangersData: "Данные о пассажирах:",
    cost: "Стоимость: ",
    passenger: "Пассажир №:",
    name: "Имя",
    surname: "Фамилия",
    phone: "Телефон",
    endTime: "Для оформления заказа оплатите его до: ",
    securityStandart:
      "Ваши платежные и личные данные надежно защищены в соответствии с международными стандартами безопасности.",
    addservices: "Дополнительные услуги",
    summ: "Сумма к оплате: ",
    pay: "Оплатить с помощью",
    return: "Условия возврата",
    booking: "Время актуального бронирования истекло",
    goHome: "Вернуться на главную страницу ",
    uah: "грн",
    success: "Оплата прошла успешно !!!",
    fail: "При оформлении билета возникла ошибка",
    number: "Номер вашего заказа ",
    call: "Свяжитесь со службой поддержки по телефону: ",
    download: " здесь*",
    addBtn: "Добавить к заказу",
    status: "Статус",
    order: "Номер заказа: ",
    forDownload:
      "Для получения билета и дополнительного сопровождения установите приложение ",
    or: " или загрузить билет",
    dontPrint: "*Для посадки распечатывать билет не обязательно",
    errorPayed: "При оплате произошла ошибка",
    errorOrder: "Не удалось найти заказ",
    errorTransaction: "Не удалось найти платежную транзакцию",
    errorError: "Упс..! Что-то пошло не так.",
    use: "использовать ",
    bonuses: " бонусов",
    payBonuses: "Оплатить бонусами",
    googleError: "Произошла ошибка при оплате"
  },

  EN: {
    trip: "Route:",
    passangersData: "Passenger data:",
    cost: " Cost:",
    passenger: "Passenger №:",
    name: "Name",
    surname: "Surname",
    phone: "Phone",
    endTime: "To place an order, pay for it before: ",
    securityStandart:
      "Your payment and personal data are reliably protected in accordance with international security standards.",
    addservices: "Additional services",
    summ: "Amount to pay",
    pay: "Pay with help",
    return: "Return conditions",
    booking: "Current booking time has expired",
    goHome: "Return to the homepage",
    uah: "uah",
    success: "The payment was successful !!!",
    fail: "An error occurred while issuing a ticket",
    number: "Your order number",
    call: "Contact support by phone: ",
    download: " here*",
    addBtn: "Add to order",
    status: "Status",
    order: "Order number: ",
    forDownload: "To receive a ticket and additional support, install the application ",
    or: " or download the ticket",
    dontPrint: "*It is not necessary to print a ticket for boarding",
    errorPayed: "An error occurred while paying",
    errorOrder: "Couldn't find order",
    errorTransaction: "Can not find payment transaction",
    errorError: "Oops..! something went wrong",
    use: "use ",
    bonuses: " of bonuses",
    payBonuses: "Pay bonuses",
    googleError: "There was an error paying"
  },

  PL: {
    trip: "Trasa:",
    passangersData: "Dane pasażera:",
    cost: "Koszt: ",
    passenger: "Pasażera №:",
    name: "Nazwa",
    surname: "Nazwisko",
    phone: "Telefon",
    endTime: "Aby złożyć zamówienie, opłać je wcześniej: ",
    securityStandart:
      "Twoje płatności i dane osobowe są bezpiecznie chronione zgodnie z międzynarodowymi standardami bezpieczeństwa.",
    addservices: "Dodatkowe usługi",
    summ: "Kwota do zapłaty",
    pay: "Płacić z pomocą",
    return: "Warunki zwrotu",
    booking: "Aktualny czas rezerwacji upłynął",
    goHome: "Wróć do strony głównej",
    uah: "uah",
    success: "Płatność się powiodła !!!",
    fail: "Wystąpił błąd podczas wystawiania biletu",
    number: "Numer Twojego zamówienia",
    call: "Skontaktuj się z obsługą klienta telefonicznie:",
    download: " tutaj*",
    addBtn: "Dodać do zamówienia",
    status: "Status",
    order: "Order number: ",
    forDownload: "Aby otrzymać zgłoszenie i dodatkowe wsparcie, zainstaluj aplikację ",
    or: " lub pobierz bilet",
    dontPrint: "*Nie ma konieczności drukowania biletu na wejście na pokład",
    errorPayed: "Wystąpił błąd podczas płacenia",
    errorOrder: "Nie udało się znaleźć zamówienia",
    errorTransaction: "Nie można znaleźć transakcji płatniczej",
    errorError: "Ups...! coś poszło nie tak",
    use: "wykorzystaj ",
    bonuses: " bonusów",
    payBonuses: "Płacić bonusów",
    googleError: "Wystąpił błąd podczas płatności"
  },
};