export const messages = {
  UK: {
    title: "Розклад автобусів",
    timeInWay: "в дорозі",
    choose: "Вибрати",
    additionals: "Детальніше",
    departure: "Відправлення",
    arrival: "Прибуття",
    sort: "Сортувати за: ",
    sortArrival: "часом прибуття",
    sortDeparture: "часом відправлення",
    sortPrice: "ціною",
    sortTime: "часом в дорозі",
  },
  RU: {
    title: "Расписание автобусов",
    timeInWay: "в пути",
    choose: "Выбрать",
    additionals: "Подробнее",
    departure: "Отправление",
    arrival: "Прибытие",
    sort: "Cортировать по: ",
    sortArrival: "времени прибытия",
    sortDeparture: "времени отправления",
    sortPrice: "цене",
    sortTime: "времени в пути",
  },
  EN: {
    title: "Bus schedule",
    timeInWay: "on the way",
    choose: "Choose",
    additionals: "More details",
    departure: "Departure",
    arrival: "Arrival",
    sort: "Sort by: ",
    sortArrival: "arrival time",
    sortDeparture: "departure time",
    sortPrice: "price",
    sortTime: "travel time",
  },
  PL: {
    title: "Rozkład jazdy autobusów",
    timeInWay: "jestem w drodze",
    choose: "Wybierz",
    additionals: "Więcej szczegółów",
    departure: "Wyjazd",
    arrival: "Przyjazd",
    sort: "Sortuj według: ",
    sortArrival: "czasu przybycia",
    sortDeparture: "czasu odjazdu",
    sortPrice: "ceny",
    sortTime: "czasu podróży",
  },
};
